#!/bin/bash

# Constants {{{1
################################################################

PROG_PATH=$(dirname $0)

# MAIN {{{1
################################################################

$PROG_PATH/../profia_wrapper.R zipfile $PROG_PATH/../test-data/input-plasFIA.zip ppmN 2 ppmGroupN 1 fracGroupN 0.1 kI 2 dataMatrix_out $PROG_PATH/output-dataMatrix.tsv

if ! diff "$PROG_PATH/output-dataMatrix.tsv" "$PROG_PATH/../test-data/output-dataMatrix.tsv" ; then
	echo "Incorrect output data matrix." >&2
	exit 1
fi
